customhost = "myflaskapprds.ces59oavef8t.us-east-1.rds.amazonaws.com"
customuser = "aws_user"
custompass = "aws_user"
customdb = "employee"
custombucket = "myflaskapp-emp"
customregion = "us-east-1"
aws_access_key_id="ASIAVZFKJLM3RA3YW3WY"
aws_secret_access_key="Ks9Av7VwsTbmq+hF5QjMQwCfE6PeaBIrSbr2ukmf"